<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PrintAgent-805e36c3-e3b6-4695-aeec-80f286e48369</UserSecretsId>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);ExamplePrintHub\**;ExampleVueClient\**;ExampleWinFormsClient\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.no_v8-no_xfa" Version="2018.4.8.256" />
    <PackageReference Include="PdfiumViewer.Native.x86.no_v8-no_xfa" Version="2018.4.8.256" />
    <PackageReference Include="PdfiumViewer.Updated" Version="2.14.5" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <Target Name="CopyPdfiumDll" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)x64\pdfium.dll" DestinationFolder="$(TargetDir)" ContinueOnError="true" />
  </Target>
</Project>
